/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedFeedbacksNewIndexRouteImport } from './routes/_authenticated/feedbacks/new/index'
import { Route as AuthenticatedFeedbacksFeedbackIdIndexRouteImport } from './routes/_authenticated/feedbacks/$feedbackId/index'
import { Route as AuthenticatedFeedbacksFeedbackIdEditRouteImport } from './routes/_authenticated/feedbacks/$feedbackId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbacksNewIndexRoute =
  AuthenticatedFeedbacksNewIndexRouteImport.update({
    id: '/feedbacks/new/',
    path: '/feedbacks/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbacksFeedbackIdIndexRoute =
  AuthenticatedFeedbacksFeedbackIdIndexRouteImport.update({
    id: '/feedbacks/$feedbackId/',
    path: '/feedbacks/$feedbackId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbacksFeedbackIdEditRoute =
  AuthenticatedFeedbacksFeedbackIdEditRouteImport.update({
    id: '/feedbacks/$feedbackId/edit',
    path: '/feedbacks/$feedbackId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/feedbacks/$feedbackId/edit': typeof AuthenticatedFeedbacksFeedbackIdEditRoute
  '/feedbacks/$feedbackId': typeof AuthenticatedFeedbacksFeedbackIdIndexRoute
  '/feedbacks/new': typeof AuthenticatedFeedbacksNewIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/feedbacks/$feedbackId/edit': typeof AuthenticatedFeedbacksFeedbackIdEditRoute
  '/feedbacks/$feedbackId': typeof AuthenticatedFeedbacksFeedbackIdIndexRoute
  '/feedbacks/new': typeof AuthenticatedFeedbacksNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/feedbacks/$feedbackId/edit': typeof AuthenticatedFeedbacksFeedbackIdEditRoute
  '/_authenticated/feedbacks/$feedbackId/': typeof AuthenticatedFeedbacksFeedbackIdIndexRoute
  '/_authenticated/feedbacks/new/': typeof AuthenticatedFeedbacksNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/dashboard'
    | '/feedbacks/$feedbackId/edit'
    | '/feedbacks/$feedbackId'
    | '/feedbacks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/dashboard'
    | '/feedbacks/$feedbackId/edit'
    | '/feedbacks/$feedbackId'
    | '/feedbacks/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/feedbacks/$feedbackId/edit'
    | '/_authenticated/feedbacks/$feedbackId/'
    | '/_authenticated/feedbacks/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedbacks/new/': {
      id: '/_authenticated/feedbacks/new/'
      path: '/feedbacks/new'
      fullPath: '/feedbacks/new'
      preLoaderRoute: typeof AuthenticatedFeedbacksNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedbacks/$feedbackId/': {
      id: '/_authenticated/feedbacks/$feedbackId/'
      path: '/feedbacks/$feedbackId'
      fullPath: '/feedbacks/$feedbackId'
      preLoaderRoute: typeof AuthenticatedFeedbacksFeedbackIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedbacks/$feedbackId/edit': {
      id: '/_authenticated/feedbacks/$feedbackId/edit'
      path: '/feedbacks/$feedbackId/edit'
      fullPath: '/feedbacks/$feedbackId/edit'
      preLoaderRoute: typeof AuthenticatedFeedbacksFeedbackIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedFeedbacksFeedbackIdEditRoute: typeof AuthenticatedFeedbacksFeedbackIdEditRoute
  AuthenticatedFeedbacksFeedbackIdIndexRoute: typeof AuthenticatedFeedbacksFeedbackIdIndexRoute
  AuthenticatedFeedbacksNewIndexRoute: typeof AuthenticatedFeedbacksNewIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedFeedbacksFeedbackIdEditRoute:
    AuthenticatedFeedbacksFeedbackIdEditRoute,
  AuthenticatedFeedbacksFeedbackIdIndexRoute:
    AuthenticatedFeedbacksFeedbackIdIndexRoute,
  AuthenticatedFeedbacksNewIndexRoute: AuthenticatedFeedbacksNewIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
